enableGlobalCache: false

enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard
  - code: YN0076
    level: discard

nmMode: hardlinks-local

nodeLinker: node-modules

npmPublishAccess: restricted

npmRegistryServer: "https://registry.yarnpkg.com"

npmScopes:
  shopify:
    npmAlwaysAuth: true
    npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@shopify/polaris@*":
    dependencies:
      "@types/react": "*"
      "@types/react-dom": "*"

preferInteractive: true
